"""Build the offline media review page from the final copy."""
from pathlib import Path
import json

root = Path(__file__).resolve().parents[1] / "yandex"
data = {lang: json.loads((root / lang / "metadata.json").read_text(encoding="utf-8")) for lang in ["ru", "en"]}
page = r'''<!doctype html>
<html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Качалка — материалы для Яндекс Игр</title>
<style>
:root{color-scheme:dark;--bg:#0c1014;--panel:#161d24;--ink:#fff4df;--muted:#9aabb8;--orange:#ff8c32;--cyan:#48d7de}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.6 "Segoe UI",Arial,sans-serif}main{max-width:1120px;margin:auto;padding:32px 28px 80px}header{display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #2a333d;padding-bottom:18px;margin-bottom:32px}.eyebrow{font-size:12px;letter-spacing:.18em;color:var(--cyan);font-weight:700}h1{font-size:clamp(30px,4vw,48px);line-height:1.12;margin:14px 0 18px;max-width:800px}h2{font-size:24px;margin:42px 0 16px}.intro{color:var(--muted);max-width:750px}button,.download{background:#28333e;border:0;border-radius:8px;color:var(--ink);padding:10px 16px;font:inherit;cursor:pointer;text-decoration:none}button.active,.download{background:var(--orange);color:#19110a;font-weight:700}button:hover,.download:hover{filter:brightness(1.14)}.hero{display:grid;grid-template-columns:1fr 220px;gap:24px;align-items:start}.hero img{width:100%;display:block;border-radius:12px}.asset-note{font-size:13px;color:var(--muted);margin-top:10px}.row{display:flex;gap:10px;flex-wrap:wrap;margin:18px 0}.video-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}video{width:100%;border-radius:10px;background:#050709;display:block}.gallery{display:grid;grid-template-columns:1fr 1fr;gap:18px}.gallery img{width:100%;border-radius:8px;display:block}.gallery a{color:var(--muted);text-decoration:none;font-size:13px}.copy-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.copy-card{background:var(--panel);border:1px solid #28333d;padding:22px;border-radius:12px}.copy-card.wide{grid-column:1/-1}.copy-head{display:flex;justify-content:space-between;align-items:center;gap:12px;font-weight:700;color:var(--cyan);margin-bottom:14px}.copy-head button{font-size:12px;padding:7px 11px}.copy{white-space:pre-wrap;line-height:1.65;margin:0}.count{color:var(--muted);font-size:12px;margin-top:14px}footer{border-top:1px solid #27313a;margin-top:46px;padding-top:18px;color:var(--muted);font-size:13px}a{color:var(--cyan)}.status{height:24px;color:var(--cyan);font-size:13px}.note{border-left:3px solid var(--orange);padding-left:16px;color:var(--muted);font-size:14px}
@media(max-width:700px){main{padding:20px 16px 50px}.hero{grid-template-columns:1fr}.hero aside{max-width:150px}.video-grid,.gallery,.copy-grid{grid-template-columns:1fr}header{gap:14px;flex-wrap:wrap}.copy-card.wide{grid-column:auto}}
</style><main>
<header><span class="eyebrow">КАРТОЧКА ДЛЯ ЯНДЕКС ИГР · 11.09.2026</span><div><button id="ru" class="active" onclick="setLanguage('ru')">Русский</button> <button id="en" onclick="setLanguage('en')">English</button></div></header>
<div class="eyebrow">ПОЙМАЙ РИТМ. ДЕРЖИ КОМБО.</div><h1 id="name"></h1><p class="intro" id="short"></p>
<div class="hero"><div><a id="cover-link"><img id="cover" alt="Обложка игры"></a><div class="asset-note">Обложка · PNG · 800 × 470</div></div><aside><a href="icon_512.png"><img src="icon_512.png" alt="Иконка игры"></a><div class="asset-note">Иконка · PNG · 512 × 512 · общая для обоих языков</div></aside></div>
<div class="row"><a class="download" id="texts-link" download>Скачать тексты</a><a id="metadata-link" class="download" download>JSON для заполнения полей</a></div>
<h2>Видео</h2><div class="video-grid"><div><video id="trailer" controls preload="metadata" playsinline></video><p class="asset-note">Проморолик · 24 сек · 1280 × 720 · титры и оригинальная музыка</p></div><div><video id="gameplay" controls preload="metadata" playsinline></video><p class="asset-note">Геймплей · 24 сек · 1280 × 720 · без добавленных титров и музыки</p></div></div>
<h2>Скриншоты для компьютера</h2><div id="gallery" class="gallery"></div>
<h2>Скриншоты с сенсорным управлением</h2><p class="asset-note">Сняты в режиме эмуляции сенсорного интерфейса, 1280 × 720. Физические телефоны в этой сессии не использовались.</p><div id="mobile-gallery" class="gallery"></div>
<h2>Тексты для карточки</h2><div class="status" id="status" aria-live="polite"></div><div id="copy-grid" class="copy-grid"></div>
<footer>Иконка и обложки — иллюстрации, созданные встроенным image_gen. Скриншоты и видео сняты в Godot с игровыми моделями и интерфейсом; для тренировок настроена съёмочная камера. Ранний и поздний прогресс записаны как отдельные эпизоды. Исходники и промпты находятся в соседней папке source.<br><a href="README.md">Состав пакета и порядок загрузки</a> · <a href="validation.json">Проверка размеров, длительности и текстовых лимитов</a></footer>
</main><script>
const DATA=__DATA__;let current='ru';
const fields=[['name','Название',50],['short_description','Короткое описание',70],['seo_description','Описание для SEO',160],['description','Об игре',1000],['how_to_play','Как играть',1000],['keywords','Ключевые слова',100]];
function setLanguage(lang){current=lang;document.querySelectorAll('header button').forEach(b=>b.classList.toggle('active',b.id===lang));document.getElementById('name').textContent=DATA[lang].name;document.getElementById('short').textContent=DATA[lang].short_description;document.getElementById('cover').src=lang+'/cover_800x470.png';document.getElementById('cover-link').href=lang+'/cover_800x470.png';document.getElementById('texts-link').href=lang+'/texts.txt';document.getElementById('metadata-link').href=lang+'/metadata.json';for(const key of ['trailer','gameplay']){const v=document.getElementById(key);v.pause();v.src=lang+'/'+key+'_24s.mp4';v.poster=lang+'/screenshots_desktop/02_explore.png'}
for(const [id,dir] of [['gallery','screenshots_desktop'],['mobile-gallery','screenshots_mobile']]){const g=document.getElementById(id);g.replaceChildren();for(const [file,label] of [['01_dumbbells','01 · Точность и комбо'],['02_explore','02 · Зал и задания'],['03_bench','03 · Жим на позднем уровне'],['04_progress','04 · Кузница титанов']]){const a=document.createElement('a');a.href=lang+'/'+dir+'/'+file+'.png';a.target='_blank';const img=document.createElement('img');img.src=a.href;img.loading='lazy';img.alt=label;a.append(img,document.createTextNode(label));g.append(a)}}
const grid=document.getElementById('copy-grid');grid.replaceChildren();for(const [key,label,max] of fields){const card=document.createElement('div');card.className='copy-card'+(['description','how_to_play'].includes(key)?' wide':'');const head=document.createElement('div');head.className='copy-head';head.textContent=label;const button=document.createElement('button');button.textContent='Копировать';button.onclick=()=>copyText(DATA[lang][key]);head.append(button);const text=document.createElement('p');text.className='copy';text.textContent=DATA[lang][key];const count=document.createElement('div');count.className='count';count.textContent=DATA[lang][key].length+' / '+max+' символов';card.append(head,text,count);grid.append(card)}}
async function copyText(text){try{await navigator.clipboard.writeText(text);document.getElementById('status').textContent='Текст скопирован.'}catch{const area=document.createElement('textarea');area.value=text;document.body.append(area);area.select();const ok=document.execCommand('copy');area.remove();document.getElementById('status').textContent=ok?'Текст скопирован.':'Выделите нужный текст и нажмите Ctrl+C.'}}
setLanguage('ru');
</script></html>'''
(root / "preview.html").write_text(page.replace("__DATA__", json.dumps(data, ensure_ascii=False)), encoding="utf-8")
print(root / "preview.html")
